# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Check
      run: make all

    - name: Build
      run: make build

    - name: Build WASM
      run: make build-wasm

    - name: Build UI
      run: make build-ui

    - name: Upload bin/luban.wasm
      uses: actions/upload-artifact@v4
      with:
        name: luban.wasm
        path: bin/luban.wasm
